version: 2

jobs:
  build:
    docker:
      - image: istio/ci:go1.9-bazel0.11
    environment:
      - BAZEL_TEST_ARGS: "--test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all"
    steps:
      - run: curl -Lo /tmp/bazel.deb https://github.com/bazelbuild/bazel/releases/download/0.15.2/bazel_0.15.2-linux-x86_64.deb && sudo dpkg -i /tmp/bazel.deb && rm /tmp/bazel.deb
      - run: sudo apt-get update && sudo apt-get install -y ninja-build pkg-config
      - checkout
      - restore_cache:
          keys:
            - bazel-cache-{{ checksum "WORKSPACE" }}
      - restore_cache:
          keys:
            - repo-cache-{{ checksum "WORKSPACE" }}
      - run: rm ~/.gitconfig
      - run: make release BAZEL_BUILD_ARGS="-j 4"
      - save_cache:
          key: repo-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.repo
      - save_cache:
          key: bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - /home/circleci/.cache/bazel
      - store_artifacts:
          path: /home/circleci/project/bazel-bin/src/envoy/envoy_tar.tar.gz
          destination: /proxy/envoy
workflows:
  version: 2
  all:
    jobs:
      - build
